.TH TCMT 1 "09 January 2000"
.SH NAME
tcmd \- Toolkit for Conceptual Modeling Daemon
.SH SYNOPSIS
.B tcmt
.SH DESCRIPTION
.B tcmt
is part of the
\fIToolkit for Conceptual Modeling (TCM)\fP.
\fItcmt\fP is not intended as a user program. 
Please use \fItcm\fP in order to display and start up all 
available tools.

.SH SEE ALSO
tcm(1)

.SH AUTHOR
Frank Dehne (frank@cs.vu.nl).

