.TH TUCD 1 "2 February 2000"
.SH NAME
tucd \- Tool for UML Use-case Diagrams 
.SH SYNOPSIS
.B tucd
.RI [ options ]
.RI [ document ]
.SH DESCRIPTION
\fItucd\fP
is an X11/Motif based graphical editor for drawing UML use-case
diagrams. Documents can be loaded from and stored to a file. It can print
documents to a PostScript printer or save as PostScript to a file.

\fItucd\fP is part of \fIThe Toolkit for Conceptual Modeling (TCM)\fP.

.SH ARGUMENTS
You can call \fItucd\fP with a single document name as argument. 
If this argument is an existing file then \fItucd\fP
tries to load a document from it. If it does not exist, a new document
is created with the argument as document name. \fItucd\fP files should
have suffix '*.ucd'.

Without a document argument, \fItucd\fP creates a new 
empty use-case diagram with the name 'untitled.ucd'.

In addition to the standard X11 toolkit options (see X11(7)), \fItucd\fP accepts
the options listed below:
.TP
.B \-drawing \fIwidth\fPx\fIheight\fP
Create a drawing area of \fIwidth\fP pixels wide and
\fIheight\fP pixels high.
.TP
.B \-help
Write all available options to standard output and quit.
.TP
.B \-maxdrawing \fIwidth\fPx\fIheight\fP
The drawing area can not be larger than \fIwidth\fP pixels wide and
\fIheight\fP pixels high.
.TP
.B \-priv_cmap 
Start the editor with a private colormap.
.TP
.B \-projdir \fIdirectory\fP 
Set the project directory (current working directory) to \fIdirectory\fP.
.TP
.B \-toPS [\fIfile\fP.ps]
Generate PostScript (to \fIfile\fP.ps or stdout when no file name was
given) and quit.
.TP
.B \-toEPS [\fIfile\fP.eps]
Generate EPS (to \fIfile\fP.eps or stdout when no file name was 
given) and quit.
.TP
.B \-toFig [\fIfile\fP.fig] [-latex]
Generate Fig format (to \fIfile\fP.fig or stdout when no file name was
given and quit. When the -latex option is given, LaTeX fonts are
generated, otherwise normal PostScript fonts are generated.
The Fig format can be read by xfig(1) and fig2dev(1).
.TP
.B \-toPNG \fIfile\fP.png
Generate PNG format to \fIfile\fP.png and quit.
.TP
.B \-toPS [\fIfile\fP.ps]
Generate PostScript (to \fIfile\fP.ps or stdout when no file name was
given) and quit.
.TP
.B \-version
Write the TCM version to standard output and quit.

.SH ENVIRONMENT
The \fBTCM_HOME\fP environment variable should be the directory
where the TCM files are installed.

.TP
.B PATH   
Should include $TCM_HOME/bin
.TP
.B MANPATH
Should include $TCM_HOME/man
.TP
.B PRINTER
Name of the default printer that is used by \fItucd\fP.
.TP
.B LD_LIBRARY_PATH
Should include $TCM_HOME/lib when the distribution contains shared
object libraries in $TCM_HOME/lib.

.SH FILES
The following relative files are relative to $TCM_HOME.
.TP
\fIbin/tucd\fP 
the use-case diagram editor.
.TP
\fIbin/psf\fP 
a program to filter PostScript output.
.TP
\fIlib/banner.ps\fP
PostScript banner page that can be used when the printer
does not print a banner page.
.TP
\fIlib/help/*\fP
The help directory contains a collection of text files for
the on-line help.
.TP
\fIlib/TCM\fP
X Resources (the same as the ones that are built-in).
You can customize the fonts and colors by setting resources
in your X defaults database.  Each string of the form
``TCM.resource:definition'' sets a resource.
.TP
.I /tmp/tcmXXXXXX
Pseudo random temporary file, for PostScript output.
.TP
\fIlib/tcm.conf\fP
TCM editor configuration file. This file contains values
for some of the editor defaults like the page size, the default 
fonts etc. This file is read by each editor upon startup.
.TP
\fI$HOME/.tcmrc\fP
Each user of TCM can override some of the options of tcm.conf
by its own configuration file, installed in $HOME/.tcmrc.


.SH SEE ALSO
Frank Dehne, Roel Wieringa and Henk van de Zandschulp -- 
TCM (Toolkit for Conceptual Modeling),
User's Guide and Reference.
This document is available as PostScript and HTML
in $TCM_HOME/doc or as HTML via the URL
http://www.cs.utwente.nl/~tcm/tcm-usersguide.html.

tcm(1), X11(7), xfig(1), fig2dev(1)

.SH AUTHOR
Frank Dehne (frank@cs.vu.nl).

.SH BUGS
Please send bug reports to tcm@cs.utwente.nl.

